version: '3.7'
services:
  nvidia-gpu-exporter:
    restart: always
    image: nvidia-server:1.2
    environment:
      LOG_LEVEL: error
      PORT: 9500
      HOST: 0.0.0.0
      INTERVAL: 5
      LOG_FILE_PATH: "/logs/gpu-server.log"
      LOG_TO_FILE: "true"
    ports:
      - 9500:9500
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/logs
